### ISSUE TITLE
feat: Refactor module implementations

### ISSUE THREAD

**Issue by bbbneo333** [jalantechnologies/boilerplate-mern#149]
- Remove `internal` - Everything should be on module root. Everything that has to be exported should be from the `index` file of the module.
- Module ideally should just have a single `service.ts`
- Simplify routing - Just have a `controller.ts` where we initialise the `router` and register the routes. Remove server and router. Remove the `rest-api` subdirectory. The app should just import the controller, get the `router` from controller instance and mount it directly on the main router.
- Simplify database implementation - A module just need to have a service and model/repository pair / entity. Remove reader, writer implementations. The model/repository pairs can reside in the `store` subdirectory.
- Remove serialisers - Use model's `toJSON` for serialising. Others can be directly serialised.

**Comment by bbbneo333** [comment]
@jjalan - I'm trying to come up with a simple approach to modules. Let me know if there's a red flag somewhere in there. Otherwise will be going with this approach.

Something similar is also being planned flask boilerplate. We will try to keep both implementation similar as possible.

**Comment by jjalan** [comment]
My concern with remove `internal` is that when a module grow, there will not be any discipline or guideline as to where to keep the things within the module and people may start putting them on the root which would make it hard to maintain. I would like to bake some opinion to make things easy to maintain.

**Comment by bbbneo333** [comment]
@jjalan :

> The advantage of keeping reader, writer again provides a guideline on where to write code that mutates an entity v/s not.

IMO - The type of mutation (read/write) that is being done on an entity does not calls out for having different files. Modules can have multiple services though in case a single service grows - but ideally that should not happen. If it needs more expansion, then you simply create a new module.

> The rest are "internal" to a module, some of which are:
crons
reader/write/db_model
controller

Again IMO - Nothing should be treated as internal. As far as a module is concerned - It's exposing everything out - controllers, crons etc. By the end of the day, they are going to be imported somewhere outside the module, right? If yes - They don't qualify to remain internal. Internals can be the one which are just being used inside the module.

**Comment by jjalan** [comment]
> Modules can have multiple services though in case a single service grows - but ideally that should not happen. If it needs more expansion, then you simply create a new module.

This is far from practice. Can someone try to work with a recent code base like to Kizuna to see various logics one module has to contain and breaking into different module is not often desired as it still revolves around one entity, business unit of the application.

> Again IMO - Nothing should be treated as internal. As far as a module is concerned - It's exposing everything out - controllers, crons etc.
The "service" or end point provided by module are public.

Before we work on this ticket, I would recommend to work at some of the applications code bases that team has to deal with please and see if there is enough guidance from the boilerplate so that a normal engineer can deviate from it easily and cause inconsistent pattern.

**Comment by bbbneo333** [comment]
> The "service" or end point provided by module are public but the code does not. This would eventually help you automate to detecting poor dependencies among module in future as well.

To be clear - I suggested the approach without the reader/writer implementations in mind. Yes - If if have reader/writer, those can remain internal.

**Comment by bbbneo333** [comment]
> This is far from practice. Can someone try to work with a recent code base like to Kizuna to see various logics one module has to contain and breaking into different module is not often desired as it still revolves around one entity, business unit of the application.

Extending module is last resort really. What I'm really suggesting is have multiple services within the module then.

**Comment by jjalan** [comment]
> What I'm really suggesting is have multiple services within the module then.

@bbbneo333  - This is an important change we are proposing and IMO, this is best discussed over a live sync with 1-2 examples from products to bring a closure to brain storm before we start on the execution on this ticket. If we want to do it to async, my recommendation is platform to try to raise a PR on a product to showcase this change before we bake this into the boilerplate. I can give 1-2 example of modules worth refactoring which are bit involved to better understand the proposal.
