### ISSUE TITLE
have the design language baked into the boilerplate, with ability to override it

### ISSUE THREAD

**Issue by ankitagrawal90** [jalantechnologies/boilerplate-mern#78]
We need to have holistic UI language for text style, buttons, input box, etc.
 
We want to ensure we have those classes and components designed first in a centralized place so everyone is then simply using them.

**Comment by jjalan** [comment]
I am closing this ticket in favor of https://github.com/jalantechnologies/boilerplate-mern/issues/91, as that has more specific tasks, while achieving the same goal listed here.
