### ISSUE TITLE
Depreciate bootstrap and add baseweb

### ISSUE THREAD

**Issue by jjalan** [jalantechnologies/boilerplate-mern#91]
Currently, application takes dependency on bootstrap npm package which is not desirable. We want to use baseweb as default UI kit.

1. Remove bootstrap, custom css and add baseweb
2. Update login page to use components from baseweb components instead of native html elements. In order to make sure baseweb integration is done well, we want sign up page to look like - https://getbootstrap.com/docs/5.3/examples/sign-in/ (minus the B logo and footer)
3. For form, use formik library to do validations

**Comment by balwant-jtc** [comment]
Complete, see this: https://github.com/jalantechnologies/boilerplate-mern/pull/92
