### ISSUE TITLE
feat: Refactor typings for repositories

### ISSUE THREAD

**Issue by bbbneo333** [jalantechnologies/boilerplate-mern#93]
- Make database models consistent and have single source of truth - Right now, there are multiple classes belonging to, example -  a UserDb/User. There should be just a single class representing an entity.
- These classes should also be serialisable - Should have a toJSON method which returns json representation of the object.

**Comment by bbbneo333** [comment]
See - https://github.com/jalantechnologies/boilerplate-mern/pull/81/files#r1472414021

**Comment by KrishnaVAMSI-2003** [comment]
The description of this ticket seems unclear and isn't properly describing the actual issue pointed out in the provided link. There is a detailed thread in the teams channel regarding this, which can be found [here](https://teams.microsoft.com/l/message/19:53290a7b3e0048099408801f0b51ae3d@thread.tacv2/1725517274002?tenantId=79836b2a-53cc-4854-81b4-ba2d7c9f2726&groupId=c0e79bd0-36ec-4b10-8be7-55f5b3d2395c&parentMessageId=1725517274002&teamName=Jalan%20Technologies&channelName=Platform%20(Team)&createdTime=1725517274002&ngc=true)

> See - https://github.com/jalantechnologies/boilerplate-mern/pull/81/files#r1472414021

I have created a separate issue(#162) for mongoose schema typings problem.

Un-assigning this issue and moving it to `no status` for now. We can pick this issue again, once confirmed with the description.
